In [ ]:
import selenium
import pandas as pd
import time

from selenium import webdriver

from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException

import re
from selenium.webdriver.common.by import By

import warnings
warnings.filterwarnings('ignore')

# 1. Scrape the details of most viewed videos on YouTube from Wikipedia.
- Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
- You need to find following details:
- A) Rank
- B) Name
- C) Artist
- D) Upload date
- E) Views

In [3]:
#connecting to driver
driver=webdriver.Chrome(r"D:\softwares\chromedriver_win32\chromedriver.exe")

#maximizing browser window
driver.maximize_window()

In [4]:
#opening wikipedia.com website
url=' https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)
time.sleep(5)

In [14]:
#scraping ranks of youtube videos

rank=[] 
try:
    ranks=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]')
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:
        rank.append('-')

In [15]:
len(rank)

30

In [16]:
name=[] 
try:
    names=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]')
    for i in names:
        name.append(i.text)
except NoSuchElementException:
        name.append('-')

In [18]:
Artist=[] 
try:
    Artists=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[3]')
    for i in Artists:
        Artist.append(i.text)
except NoSuchElementException:
        Artist.append('-')

In [19]:
len(Artist)

30

In [20]:
upload_date=[] 
try:
    upload_dates=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[4]')
    for i in upload_dates:
        upload_date.append(i.text)
except NoSuchElementException:
        upload_date.append('-')

In [21]:
views=[] 
try:
    viewss=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[5]')
    for i in viewss:
        views.append(i.text)
except NoSuchElementException:
        views.append('-')

In [26]:
youtube_videos=pd.DataFrame({'Rank':rank,'Name':name,'Artist':Artist,'Upload date':upload_date,'views':views})
youtube_videos

,Rank,Name,Artist,Upload date,views
0,1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,11.74,"June 17, 2016"
1,2.,"""Despacito""[7]",Luis Fonsi,8.01,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,6.53,"October 8, 2016"
3,4.,"""Shape of You""[15]",Ed Sheeran,5.85,"January 30, 2017"
4,5.,"""Bath Song""[17]",Cocomelon – Nursery Rhymes,5.77,"May 2, 2018"
5,6.,"""See You Again""[18]",Wiz Khalifa,5.70,"April 6, 2015"
6,7.,"""Phonics Song with Two Words""[23]",ChuChu TV,5.02,"March 6, 2014"
7,8.,"""Uptown Funk""[24]",Mark Ronson,4.76,"November 19, 2014"
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[25]",Miroshka TV,4.73,"February 27, 2018"
9,10.,"""Wheels on the Bus""[26]",Cocomelon – Nursery Rhymes,4.63,"May 24, 2018"
10,11.,"""Gangnam Style""[27]",Psy,4.61,"July 15, 2012"
11,12.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,4.51,"January 31, 2012"
12,13.,"""Dame Tu Cosita""[33]",El Chombo,4.14,"April 5, 2018"
13,14.,"""Sugar""[34]",Maroon 5,3.78,"January 14, 2015"
14,15.,"""Roar""[35]",Katy Perry,3.69,"September 5, 2013"
15,16.,"""Counting Stars""[36]",OneRepublic,3.68,"May 31, 2013"
16,17.,"""Axel F""[37]",Crazy Frog,3.61,"June 16, 2009"
17,18.,"""Sorry""[38]",Justin Bieber,3.61,"October 22, 2015"
18,19.,"""Thinking Out Loud""[39]",Ed Sheeran,3.52,"October 7, 2014"
19,20.,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,3.43,"June 25, 2018"
20,21.,"""Dark Horse""[41]",Katy Perry,3.40,"February 20, 2014"
21,22.,"""Faded""[42]",Alan Walker,3.37,"December 3, 2015"
22,23.,"""Girls Like You""[43]",Maroon 5,3.35,"May 31, 2018"
23,24.,"""Let Her Go""[44]",Passenger,3.34,"July 25, 2012"
24,25.,"""Waka Waka (This Time for Africa)""[45]",Shakira,3.31,"June 4, 2010"
25,26.,"""Perfect""[46]",Ed Sheeran,3.30,"November 9, 2017"
26,27.,"""Bailando""[47]",Enrique Iglesias,3.30,"April 11, 2014"
27,28.,"""Lean On""[48]",Major Lazer,3.29,"March 22, 2015"
28,29.,"""Humpty the train on a fruits ride""[49]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,3.23,"January 26, 2018"
29,30.,"""Shake It Off""[50]",Taylor Swift,3.23,"August 18, 2014"

In [28]:
driver.close()

# 2. Scrape the details team India’s international fixtures from bcci.tv.
- Url = https://www.bcci.tv/.
- You need to find following details:
- A) Match title (I.e. 1st ODI)
- B) Series
- C) Place
- D) Date
- E) Time
- Note: - From bcci.tv home page you have reach to the international fixture page through code

In [54]:
#connecting to driver
driver=webdriver.Chrome(r"D:\softwares\chromedriver_win32\chromedriver.exe")

#maximizing browser window
driver.maximize_window()

In [56]:
#opening guru99.com website
url='  https://www.bcci.tv/'
driver.get(url)
time.sleep(5)

In [57]:
tab=driver.find_element(By.XPATH,'/html/body/nav/div[1]/button/span[1]')
tab.click()

In [64]:
int_btn=driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]')
int_btn.click()

In [62]:
url=[]
link=driver.find_elements(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
for i in link:
    url.append(i.get_attribute('href'))

In [63]:
url

['https://www.bcci.tv/international/fixtures']

In [77]:
cat_btn=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div/div[1]')
cat_btn.click()

In [78]:
women_select=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div[1]/div/div[2]/div[3]')
women_select.click()

In [79]:
tour_tab=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div[1]')
tour_tab.click()

In [80]:
aus_tour=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div[3]')
aus_tour.click()

In [110]:
series=[]
for i in url:
    driver.get(i)
    time.sleep(10)
    try:
        seriess=driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
        for u in seriess:
            series.append(u.text)
    except NoSuchElementException:
        series.append('-')

In [111]:
series

['AUSTRALIA WOMEN TOUR OF INDIA 2022',
 'AUSTRALIA WOMEN TOUR OF INDIA 2022',
 'AUSTRALIA WOMEN TOUR OF INDIA 2022',
 'AUSTRALIA WOMEN TOUR OF INDIA 2022',
 'AUSTRALIA WOMEN TOUR OF INDIA 2022']

In [106]:
title=[]
for i in url:
    driver.get(i)
    time.sleep(10)
    try:
        titles=driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
        for u in titles:
            title.append(u.text)
    except NoSuchElementException:
        title.append('-')

In [107]:
title

['1st T20I -', '2nd T20I -', '3rd T20I -', '4th T20I -', '5th T20I -']

In [112]:
date=[]
for i in url:
    driver.get(i)
    time.sleep(10)
    try:
        titles=driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]')
        for u in titles:
            date.append(u.text)
    except NoSuchElementException:
        date.append('-')

In [113]:
date

['9 DEC 2022', '11 DEC 2022', '14 DEC 2022', '17 DEC 2022', '20 DEC 2022']

In [117]:
times=[]
for i in url:
    driver.get(i)
    time.sleep(10)
    try:
        titles=driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]')
        for u in titles:
            times.append(u.text)
    except NoSuchElementException:
        times.append('-')

In [118]:
times

['7:00 PM IST', '7:00 PM IST', '7:00 PM IST', '7:00 PM IST', '7:00 PM IST']

In [128]:
place=[]
for i in url:
    driver.get(i)
    time.sleep(10)
    try:
        titles=driver.find_elements(By.XPATH,'//div[@class="fix-place ng-binding ng-scope"]')
        for u in titles:
            place.append(u.text.split(' ')[-1:])
    except NoSuchElementException:
        place.append('-')

In [129]:
place

[['MUMBAI'], ['MUMBAI'], ['Mumbai'], ['Mumbai'], ['Mumbai']]

In [130]:
bcci_data=pd.DataFrame({'Match title':title,'Series':series,'Place':place,'Date':date,'Time':time})
bcci_data

,Match title,Series,Place,Date,Time
0,1st T20I -,AUSTRALIA WOMEN TOUR OF INDIA 2022,[MUMBAI],9 DEC 2022,<module 'time' (built-in)>
1,2nd T20I -,AUSTRALIA WOMEN TOUR OF INDIA 2022,[MUMBAI],11 DEC 2022,<module 'time' (built-in)>
2,3rd T20I -,AUSTRALIA WOMEN TOUR OF INDIA 2022,[Mumbai],14 DEC 2022,<module 'time' (built-in)>
3,4th T20I -,AUSTRALIA WOMEN TOUR OF INDIA 2022,[Mumbai],17 DEC 2022,<module 'time' (built-in)>
4,5th T20I -,AUSTRALIA WOMEN TOUR OF INDIA 2022,[Mumbai],20 DEC 2022,<module 'time' (built-in)>

In [131]:
driver.close()

# 3. Scrape the details of selenium exception from guru99.com.**
- Url = https://www.guru99.com/
- You need to find following details:
- A) Name
- B) Description
- Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [146]:
#connecting to driver
driver=webdriver.Chrome(r"D:\softwares\chromedriver_win32\chromedriver.exe")

#maximizing browser window
driver.maximize_window()

In [147]:
#opening guru99.com website
url=' https://www.guru99.com/'
driver.get(url)
time.sleep(5)

In [148]:
search_bar=driver.find_element(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[1]/div/table/tbody/tr/td[1]/input')
search_bar.send_keys('Selenium exception handling')

search_button=driver.find_element(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[2]/button')
search_button.click()

In [149]:
search_option=driver.find_element(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/div[1]/div[6]/div[2]/div/div/div[1]/div[1]/div[1]/div[1]/div/a')
search_option.click()

In [150]:
#scraping url
url=[]

brand_url=driver.find_elements(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/div[1]/div[6]/div[2]/div/div/div[1]/div[1]/div[1]/div[1]/div/a')
for i in brand_url:
    url.append(i.get_attribute('href'))

In [151]:
url

['https://www.guru99.com/exception-handling-selenium.html']

In [152]:
name=[] 
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        names=driver.find_elements(By.XPATH,'//div[@class="entry-content single-content"]/p/strong')
        for i in names:
            name.append(i.text)
    except NoSuchElementException:
        name.append('-')

In [154]:
len(name)

47

In [156]:
name[:41]

['1. ElementNotVisibleException:',
 '2. ElementNotSelectableException:',
 '3. NoSuchElementException:',
 '4. NoSuchFrameException:',
 '5. NoAlertPresentException:',
 '6. NoSuchWindowException:',
 '7. StaleElementReferenceException:',
 '8. SessionNotFoundException:',
 '9. TimeoutException:',
 '10. WebDriverException:',
 '11. ConnectionClosedException:',
 '12. ElementClickInterceptedException:',
 '13. ElementNotInteractableException:',
 '14. ErrorInResponseException:',
 '15. ErrorHandler.UnknownServerException:',
 '16. ImeActivationFailedException:',
 '17. ImeNotAvailableException:',
 '18. InsecureCertificateException:',
 '19. InvalidArgumentException:',
 '20. InvalidCookieDomainException:',
 '21. InvalidCoordinatesException:',
 '22. InvalidElementStateException:',
 '23. InvalidSessionIdException:',
 '24. InvalidSwitchToTargetException:',
 '25. JavascriptException:',
 '26. JsonException:',
 '27. NoSuchAttributeException:',
 '28. MoveTargetOutOfBoundsException:',
 '29. NoSuchContextException:',
 '30. NoSuchCookieException:',
 '31. NotFoundException:',
 '32. RemoteDriverServerException:',
 '33. ScreenshotException:',
 '34. SessionNotCreatedException:',
 '35. UnableToSetCookieException:',
 '36. UnexpectedTagNameException:',
 '37. UnhandledAlertException:',
 '38. UnexpectedAlertPresentException:',
 '39. UnknownMethodException:',
 '40. UnreachableBrowserException:',
 '41. UnsupportedCommandException:']

In [158]:
descriptions=[] 
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        description=driver.find_elements(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div/p')
        for i in description:
            descriptions.append(i.text.split(':')[1:])
    except NoSuchElementException:
        descriptions.append('-')

In [160]:
len(descriptions)

53

In [159]:
descriptions[:41]

[[' This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.'],
 [' This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.'],
 [' This Exception occurs if an element could not be found.'],
 [' This Exception occurs if the frame target to be switched to does not exist.'],
 [' This Exception occurs when you switch to no presented alert.'],
 [' This Exception occurs if the window target to be switch does not exist.'],
 [' This Selenium exception occurs happens when the web element is detached from the current DOM.'],
 [' The WebDriver is acting after you quit the browser.'],
 [' Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn’t found in the specified time.'],
 [' This Exception takes place when the WebDriver is acting right after you close the browser.'],
 [' This type of Exception takes place when there is a disconnection in the driver.'],
 [' The command may not be completed as the element receiving the events is concealing the element which was requested clicked.'],
 [' This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.'],
 [' This happens while interacting with the Firefox extension or the remote driver server.'],
 [' Exception is used as a placeholder in case if the server returns an error without a stack trace.'],
 [' This expectation will occur when IME engine activation has failed.'],
 [' It takes place when IME support is unavailable.'],
 [' Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.'],
 [' It occurs when an argument does not belong to the expected type.'],
 [' This happens when you try to add a cookie under a different domain instead of current URL.'],
 [' This type of Exception matches an interacting operation that is not valid.'],
 [' It occurs when command can’t be finished when the element is invalid.'],
 [' This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.'],
 [' This occurs when the frame or window target to be switched does not exist.'],
 [' This issue occurs while executing JavaScript given by the user.'],
 [' It occurs when you afford to get the session when the session is not created.'],
 [' This kind of Exception occurs when the attribute of an element could not be found.'],
 [' It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.'],
 [' ContextAware does mobile device testing.'],
 [' This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.'],
 [' This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.'],
 [' This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.'],
 [' It is not possible to capture a screen.'],
 [' It happens when a new session could not be successfully created.'],
 [' This occurs if a driver is unable to set a cookie.'],
 [' Happens if a support class did not get a web element as expected.'],
 [' This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.'],
 [' It occurs when there is the appearance of an unexpected alert.'],
 [' This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.'],
 [' This Exception occurs only when the browser is not able to be opened or crashed because of some reason.'],
 [' This occurs when remote WebDriver doesn’t send valid commands as expected.']]

In [161]:
data=pd.DataFrame({'Exception name':name[:41],'description':descriptions[:41]})
data

,Exception name,description
0,1. ElementNotVisibleException:,[ This type of Selenium exception occurs when ...
1,2. ElementNotSelectableException:,[ This Selenium exception occurs when an eleme...
2,3. NoSuchElementException:,[ This Exception occurs if an element could no...
3,4. NoSuchFrameException:,[ This Exception occurs if the frame target to...
4,5. NoAlertPresentException:,[ This Exception occurs when you switch to no ...
5,6. NoSuchWindowException:,[ This Exception occurs if the window target t...
6,7. StaleElementReferenceException:,[ This Selenium exception occurs happens when ...
7,8. SessionNotFoundException:,[ The WebDriver is acting after you quit the b...
8,9. TimeoutException:,[ Thrown when there is not enough time for a c...
9,10. WebDriverException:,[ This Exception takes place when the WebDrive...
10,11. ConnectionClosedException:,[ This type of Exception takes place when ther...
11,12. ElementClickInterceptedException:,[ The command may not be completed as the elem...
12,13. ElementNotInteractableException:,[ This Selenium exception is thrown when any e...
13,14. ErrorInResponseException:,[ This happens while interacting with the Fire...
14,15. ErrorHandler.UnknownServerException:,[ Exception is used as a placeholder in case i...
15,16. ImeActivationFailedException:,[ This expectation will occur when IME engine ...
16,17. ImeNotAvailableException:,[ It takes place when IME support is unavailab...
17,18. InsecureCertificateException:,[ Navigation made the user agent to hit a cert...
18,19. InvalidArgumentException:,[ It occurs when an argument does not belong t...
19,20. InvalidCookieDomainException:,[ This happens when you try to add a cookie un...
20,21. InvalidCoordinatesException:,[ This type of Exception matches an interactin...
21,22. InvalidElementStateException:,[ It occurs when command can’t be finished whe...
22,23. InvalidSessionIdException:,[ This Exception took place when the given ses...
23,24. InvalidSwitchToTargetException:,[ This occurs when the frame or window target ...
24,25. JavascriptException:,[ This issue occurs while executing JavaScript...
25,26. JsonException:,[ It occurs when you afford to get the session...
26,27. NoSuchAttributeException:,[ This kind of Exception occurs when the attri...
27,28. MoveTargetOutOfBoundsException:,[ It takes place if the target provided to the...
28,29. NoSuchContextException:,[ ContextAware does mobile device testing.]
29,30. NoSuchCookieException:,[ This Exception occurs when no cookie matchin...
30,31. NotFoundException:,[ This Exception is a subclass of WebDriverExc...
31,32. RemoteDriverServerException:,[ This Selenium exception is thrown when the s...
32,33. ScreenshotException:,[ It is not possible to capture a screen.]
33,34. SessionNotCreatedException:,[ It happens when a new session could not be s...
34,35. UnableToSetCookieException:,[ This occurs if a driver is unable to set a c...
35,36. UnexpectedTagNameException:,[ Happens if a support class did not get a web...
36,37. UnhandledAlertException:,[ This expectation occurs when there is an ale...
37,38. UnexpectedAlertPresentException:,[ It occurs when there is the appearance of an...
38,39. UnknownMethodException:,[ This Exception happens when the requested co...
39,40. UnreachableBrowserException:,[ This Exception occurs only when the browser ...
40,41. UnsupportedCommandException:,[ This occurs when remote WebDriver doesn’t se...

In [162]:
driver.close()

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.**
- Url = http://statisticstimes.com/
- You have to find following details:
- A) Rank
- B) State
- C) GSDP(18-19)- at current prices
- D) GSDP(19-20)- at current prices
- E) Share(18-19)
- F) GDP($ billion)
- Note: - From statisticstimes home page you have to reach to economy page through code.

In [2]:
#connecting to driver
driver=webdriver.Chrome(r"D:\softwares\chromedriver_win32\chromedriver.exe")

#maximizing browser window
driver.maximize_window()

In [3]:
#opening statisticstime.com page
url='https://www.statisticstimes.com/'
driver.get(url)
time.sleep(5)

In [4]:
drop_down=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
drop_down.click()

In [5]:
india_click=driver.find_element(By.XPATH,'//div[@class="dropdown"][2]/div/a[3]')
india_click.click()

In [8]:
url=[]
link=driver.find_elements(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
for i in link:
    url.append(i.get_attribute('href'))

In [9]:
url

['https://www.statisticstimes.com/economy/india/indian-states-gdp.php']

In [10]:
indian_states=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
indian_states.click()

In [11]:
rank=[]
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        ranks=driver.find_elements(By.XPATH,'//td[@class="data1"]')
        for u in ranks:
            rank.append(u.text)
    except NoSUchElementException:
        rank.append('-')

In [13]:
state=[]
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        states=driver.find_elements(By.XPATH,'//td[@class="name"]')
        for u in states:
            state.append(u.text)
    except NoSUchElementException:
        state.append('-')

In [15]:
gsdp1920=[]
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        gsdp1920s=driver.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]/table/tbody/tr/td[3]')
        for u in gsdp1920s:
            gsdp1920.append(u.text)
    except NoSUchElementException:
        gsdp1920.append('-')

In [18]:
gsdp1819=[]
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        gsdp1819s=driver.find_elements(By.XPATH,'//td[@class="data sorting_1"]')
        for u in gsdp1819s:
            gsdp1819.append(u.text)
    except NoSUchElementException:
        gsdp1819.append('-')

In [26]:
share=[]
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        shares=driver.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]/table/tbody/tr/td[5]')
        for u in shares:
            share.append(u.text)
    except NoSuchElementException:
        share.append('-')

In [32]:
GDP=[]
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        GDPs=driver.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]/table/tbody/tr/td[6]')
        for u in GDPs:
            GDP.append(u.text)
    except NoSuchElementException:
        GDP.append('-')

In [36]:
statistics=pd.DataFrame({'Rank':rank[:33],'State':state[:33],'GSDP 19-20':gsdp1920[:33],'GSDP 18-19':gsdp1819[:33],
                         'Share':share[:33],'GDP':GDP[:33]})
statistics

   Rank                      State GSDP 19-20 GSDP 18-19   Share      GDP
0     1                Maharashtra          -  2,632,792  13.94%  399.921
1     2                 Tamil Nadu  1,845,853  1,630,208   8.63%  247.629
2     3              Uttar Pradesh  1,687,818  1,584,764   8.39%  240.726
3     4                    Gujarat          -  1,502,899   7.96%  228.290
4     5                  Karnataka  1,631,977  1,493,127   7.91%  226.806
5     6                West Bengal  1,253,832  1,089,898   5.77%  165.556
6     7                  Rajasthan  1,020,989    942,586   4.99%  143.179
7     8             Andhra Pradesh    972,782    862,957   4.57%  131.083
8     9                  Telangana    969,604    861,031   4.56%  130.791
9    10             Madhya Pradesh    906,672    809,592   4.29%  122.977
10   11                     Kerala          -    781,653   4.14%  118.733
11   12                      Delhi    856,112    774,870   4.10%  117.703
12   13                    Haryana    831,610    734,163   3.89%  111.519
13   14                      Bihar    611,804    530,363   2.81%   80.562
14   15                     Punjab    574,760    526,376   2.79%   79.957
15   16                     Odisha    521,275    487,805   2.58%   74.098
16   17                      Assam          -    315,881   1.67%   47.982
17   18               Chhattisgarh    329,180    304,063   1.61%   46.187
18   19                  Jharkhand    328,598    297,204   1.57%   45.145
19   20                Uttarakhand          -    245,895   1.30%   37.351
20   21            Jammu & Kashmir          -    155,956   0.83%   23.690
21   22           Himachal Pradesh    165,472    153,845   0.81%   23.369
22   23                        Goa     80,449     73,170   0.39%   11.115
23   24                    Tripura     55,984     49,845   0.26%    7.571
24   25                 Chandigarh          -     42,114   0.22%    6.397
25   26                 Puducherry     38,253     34,433   0.18%    5.230
26   27                  Meghalaya     36,572     33,481   0.18%    5.086
27   28                     Sikkim     32,496     28,723   0.15%    4.363
28   29                    Manipur     31,790     27,870   0.15%    4.233
29   30                   Nagaland          -     27,283   0.14%    4.144
30   31          Arunachal Pradesh          -     24,603   0.13%    3.737
31   32                    Mizoram     26,503     22,287   0.12%    3.385
32   33  Andaman & Nicobar Islands          -          -       -        -

In [37]:
driver.close()

# 5. Scrape the details of trending repositories on Github.com.
- Url = https://github.com/
- You have to find the following details:
- A) Repository title
- B) Repository description
- C) Contributors count
- D) Language used

In [38]:
#connecting to driver
driver=webdriver.Chrome(r"D:\softwares\chromedriver_win32\chromedriver.exe")

#maximizing browser window
driver.maximize_window()

In [39]:
#opening github.com page
url='https://github.com/'
driver.get(url)
time.sleep(5)

In [40]:
tab_btn=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/button/span')
tab_btn.click()

In [51]:
os_btn=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
os_btn.click()

In [43]:
url=[]
link=driver.find_elements(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a')
for i in link:
    url.append(i.get_attribute('href'))

In [44]:
url

['https://github.com/trending']

In [52]:
trending_btn=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a')
trending_btn.click()

In [56]:
#extracting Repository title
title=[]
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        title_tags=driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]')
        for u in title_tags:
            title.append(u.text.split("/")[1])
    except NoSuchElementException:
        title.append('-')

In [57]:
len(title)

25

In [58]:
title

[' InvokeAI',
 ' ml-stable-diffusion',
 ' snarkOS',
 ' misskey',
 ' klipper',
 ' cs-self-learning',
 ' whatsapp-gpt',
 ' awesome-english-ebooks',
 ' Book4_Power-of-Matrix',
 ' go-coffeeshop',
 ' monica',
 ' lede',
 ' awesome-advent-of-code',
 ' palera1n',
 ' create-t3-app',
 ' easytrojan',
 ' openai-quickstart-node',
 ' PowerToys',
 ' go-clean-template',
 ' zfs',
 ' cloudstream',
 ' advent-of-code-rust',
 ' You-Dont-Know-JS',
 ' openai-quickstart-python',
 ' xilem']

In [59]:
#extracting Repository description
description=[]
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        description_tags=driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
        for u in description_tags:
            description.append(u.text)
    except NoSuchElementException:
        description.append('-')

In [60]:
len(description)

24

In [61]:
description

['This version of Stable Diffusion features a slick WebGUI, an interactive command-line script that combines text2img and img2img functionality in a "dream bot" style interface, and multiple features and other enhancements. For more info, see the website link below.',
 'Stable Diffusion with Core ML on Apple Silicon',
 'A Decentralized Operating System for ZK Applications',
 '🌎 An interplanetary microblogging platform 🚀',
 'Klipper is a 3d-printer firmware',
 '计算机自学指南',
 '经济学人(含音频)、纽约客、卫报、连线、大西洋月刊等英语杂志免费下载,支持epub、mobi、pdf格式, 每周更新',
 'Book_4_《矩阵力量》 | 鸢尾花书：从加减乘除到机器学习；本册有，584幅图，81个代码文件，其中18个Streamlit App；状态：清华社五审五校中；Github稿件基本稳定，欢迎提意见，会及时修改',
 '☕ A practical event-driven microservices demo built with Golang. Nomad, Consul Connect, Vault, and Terraform for deployment',
 'Personal CRM. Remember everything about your friends, family and business relationships.',
 "Lean's LEDE source",
 'A collection of awesome resources related to the yearly Advent of Code challenge.',
 'iOS 15.0-15.7.1 (semi-)tethered checkm8 "jailbreak"',
 'The best way to start a full-stack, typesafe Next.js app',
 '世界上最简单的Trojan部署脚本，仅需一行命令即可搭建一台代理服务器',
 'Node.js example app from the OpenAI API quickstart tutorial',
 'Windows system utilities to maximize productivity',
 'Clean Architecture template for Golang services',
 'OpenZFS on Linux and FreeBSD',
 'Android app for streaming and downloading Movies, TV-Series and Anime.',
 '🎄Starter template for solving Advent of Code in Rust.',
 'A book series on JavaScript. @YDKJS on twitter.',
 'Python example app from the OpenAI API quickstart tutorial',
 'An experimental Rust native UI framework']

In [62]:
#extracting Repository description
ccount=[]
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        ccounts=driver.find_elements(By.XPATH,'//img[@class="avatar mb-1 avatar-user"]')
        for u in ccounts:
            ccount.append(u.get_attribute('src'))
    except NoSuchElementException:
        ccount.append('-')

In [63]:
ccount

['https://avatars.githubusercontent.com/u/111189?s=40&v=4',
 'https://avatars.githubusercontent.com/u/40327258?s=40&v=4',
 'https://avatars.githubusercontent.com/u/4822129?s=40&v=4',
 'https://avatars.githubusercontent.com/u/3865161?s=40&v=4',
 'https://avatars.githubusercontent.com/u/54517381?s=40&v=4',
 'https://avatars.githubusercontent.com/u/64497909?s=40&v=4',
 'https://avatars.githubusercontent.com/u/6166296?s=40&v=4',
 'https://avatars.githubusercontent.com/u/9260812?s=40&v=4',
 'https://avatars.githubusercontent.com/u/14917648?s=40&v=4',
 'https://avatars.githubusercontent.com/u/3750347?s=40&v=4',
 'https://avatars.githubusercontent.com/u/13221615?s=40&v=4',
 'https://avatars.githubusercontent.com/u/8600837?s=40&v=4',
 'https://avatars.githubusercontent.com/u/4439005?s=40&v=4',
 'https://avatars.githubusercontent.com/u/30769358?s=40&v=4',
 'https://avatars.githubusercontent.com/u/10798641?s=40&v=4',
 'https://avatars.githubusercontent.com/u/20679825?s=40&v=4',
 'https://avatars.githubusercontent.com/u/3004890?s=40&v=4',
 'https://avatars.githubusercontent.com/u/9563098?s=40&v=4',
 'https://avatars.githubusercontent.com/u/53491797?s=40&v=4',
 'https://avatars.githubusercontent.com/u/1433580?s=40&v=4',
 'https://avatars.githubusercontent.com/u/4352664?s=40&v=4',
 'https://avatars.githubusercontent.com/u/60659728?s=40&v=4',
 'https://avatars.githubusercontent.com/u/15178800?s=40&v=4',
 'https://avatars.githubusercontent.com/u/40034814?s=40&v=4',
 'https://avatars.githubusercontent.com/u/50735120?s=40&v=4',
 'https://avatars.githubusercontent.com/u/42030331?s=40&v=4',
 'https://avatars.githubusercontent.com/u/279531?s=40&v=4',
 'https://avatars.githubusercontent.com/u/119705166?s=40&v=4',
 'https://avatars.githubusercontent.com/u/1683811?s=40&v=4',
 'https://avatars.githubusercontent.com/u/105787223?s=40&v=4',
 'https://avatars.githubusercontent.com/u/422341?s=40&v=4',
 'https://avatars.githubusercontent.com/u/25419741?s=40&v=4',
 'https://avatars.githubusercontent.com/u/61099?s=40&v=4',
 'https://avatars.githubusercontent.com/u/40141970?s=40&v=4',
 'https://avatars.githubusercontent.com/u/31687149?s=40&v=4',
 'https://avatars.githubusercontent.com/u/42570690?s=40&v=4',
 'https://avatars.githubusercontent.com/u/70857188?s=40&v=4',
 'https://avatars.githubusercontent.com/u/9948313?s=40&v=4',
 'https://avatars.githubusercontent.com/u/22235437?s=40&v=4',
 'https://avatars.githubusercontent.com/u/43347?s=40&v=4',
 'https://avatars.githubusercontent.com/u/65916846?s=40&v=4',
 'https://avatars.githubusercontent.com/u/1736154?s=40&v=4',
 'https://avatars.githubusercontent.com/u/16900547?s=40&v=4',
 'https://avatars.githubusercontent.com/u/1478102?s=40&v=4',
 'https://avatars.githubusercontent.com/u/18669106?s=40&v=4',
 'https://avatars.githubusercontent.com/u/87825638?s=40&v=4',
 'https://avatars.githubusercontent.com/u/84083936?s=40&v=4',
 'https://avatars.githubusercontent.com/u/56302322?s=40&v=4',
 'https://avatars.githubusercontent.com/u/42699250?s=40&v=4',
 'https://avatars.githubusercontent.com/u/51714798?s=40&v=4',
 'https://avatars.githubusercontent.com/u/95541290?s=40&v=4',
 'https://avatars.githubusercontent.com/u/8353666?s=40&v=4',
 'https://avatars.githubusercontent.com/u/37516851?s=40&v=4',
 'https://avatars.githubusercontent.com/u/55907257?s=40&v=4',
 'https://avatars.githubusercontent.com/u/3386752?s=40&v=4',
 'https://avatars.githubusercontent.com/u/875591?s=40&v=4',
 'https://avatars.githubusercontent.com/u/1462282?s=40&v=4',
 'https://avatars.githubusercontent.com/u/1169912?s=40&v=4',
 'https://avatars.githubusercontent.com/u/1725475?s=40&v=4',
 'https://avatars.githubusercontent.com/u/26427004?s=40&v=4',
 'https://avatars.githubusercontent.com/u/1828123?s=40&v=4',
 'https://avatars.githubusercontent.com/u/55826637?s=40&v=4',
 'https://avatars.githubusercontent.com/u/64327779?s=40&v=4',
 'https://avatars.githubusercontent.com/u/448040?s=40&v=4',
 'https://avatars.githubusercontent.com/u/1643797?s=40&v=4',
 'https://avatars.githubusercontent.com/u/148917?s=40&v=4',
 'https://avatars.githubusercontent.com/u/6709544?s=40&v=4',
 'https://avatars.githubusercontent.com/u/5410316?s=40&v=4',
 'https://avatars.githubusercontent.com/u/1386373?s=40&v=4',
 'https://avatars.githubusercontent.com/u/799124?s=40&v=4',
 'https://avatars.githubusercontent.com/u/11805592?s=40&v=4',
 'https://avatars.githubusercontent.com/u/46196380?s=40&v=4',
 'https://avatars.githubusercontent.com/u/65916846?s=40&v=4',
 'https://avatars.githubusercontent.com/u/53124886?s=40&v=4',
 'https://avatars.githubusercontent.com/u/18114966?s=40&v=4',
 'https://avatars.githubusercontent.com/u/1682504?s=40&v=4',
 'https://avatars.githubusercontent.com/u/22272449?s=40&v=4',
 'https://avatars.githubusercontent.com/u/33934311?s=40&v=4',
 'https://avatars.githubusercontent.com/u/150330?s=40&v=4',
 'https://avatars.githubusercontent.com/u/3682072?s=40&v=4',
 'https://avatars.githubusercontent.com/u/5736113?s=40&v=4',
 'https://avatars.githubusercontent.com/u/8932386?s=40&v=4',
 'https://avatars.githubusercontent.com/u/1768718?s=40&v=4',
 'https://avatars.githubusercontent.com/u/3386752?s=40&v=4',
 'https://avatars.githubusercontent.com/u/242367?s=40&v=4',
 'https://avatars.githubusercontent.com/u/420008?s=40&v=4',
 'https://avatars.githubusercontent.com/u/25784?s=40&v=4',
 'https://avatars.githubusercontent.com/u/36049421?s=40&v=4',
 'https://avatars.githubusercontent.com/u/951129?s=40&v=4']

In [76]:
#extracting Repository languages
language=[]
for i in url:
    driver.get(i)
    time.sleep(2)
    try:
        languages=driver.find_elements(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]')
        for u in languages:
            language.append(u.text)
    except NoSuchElementException:
        language.append('-')

In [77]:
language

['Jupyter Notebook',
 'Python',
 'Rust',
 'TypeScript',
 'C',
 'HTML',
 'Go',
 'CSS',
 'Python',
 'Go',
 'PHP',
 'C',
 'Shell',
 'TypeScript',
 'Shell',
 'JavaScript',
 'C#',
 'Go',
 'C',
 'Kotlin',
 'Rust',
 'CSS',
 'Rust']

In [78]:
driver.close()

# 6. Scrape the details of top 100 songs on billiboard.com.
- Url = https:/www.billboard.com/
- You have to find the following details:
- A) Song name
- B) Artist name
- C) Last week rank
- D) Peak rank
- E) Weeks on board
- Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [79]:
#connecting to driver
driver=webdriver.Chrome(r"D:\softwares\chromedriver_win32\chromedriver.exe")

#maximizing browser window
driver.maximize_window()

In [80]:
#opening github.com page
url='https:/www.billboard.com/'
driver.get(url)
time.sleep(2)

In [83]:
tab_btn=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[4]/div/div[1]/div[1]/button')
tab_btn.click()

In [84]:
chart_btn=driver.find_element(By.XPATH,'/html/body/div[3]/div[7]/div/div/div/ul/li[1]/h3/a')
chart_btn.click()

In [87]:
#getting link of the top100 page
url=[]
link=driver.find_elements(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a')
for i in link:
    url.append(i.get_attribute('href'))

In [88]:
url

['https://www.billboard.com/charts/hot-100/']

In [89]:
top100_btn=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a')
top100_btn.click()

In [97]:
name=[]
for i in url:
    driver.get(i)
    time.sleep(3)
    try:
        names=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li/h3')
        for u in names:
            name.append(u.text)
    except NoSuchElementException:
        name.append('-')

In [98]:
name

['Anti-Hero',
 'Rich Flex',
 'Unholy',
 'Bad Habit',
 'All I Want For Christmas Is You',
 "Rockin' Around The Christmas Tree",
 "I'm Good (Blue)",
 'As It Was',
 'Jingle Bell Rock',
 'A Holly Jolly Christmas',
 'Lift Me Up',
 'Die For You',
 'You Proof',
 'Under The Influence',
 'Super Freaky Girl',
 'Cuff It',
 'Something In The Orange',
 'I Like You (A Happier Song)',
 "It's The Most Wonderful Time Of The Year",
 'Wasted On You',
 'Just Wanna Rock',
 'Tomorrow 2',
 'Last Christmas',
 'Made You Look',
 'Vegas',
 'Lavender Haze',
 "I Ain't Worried",
 'Titi Me Pregunto',
 'Wait For U',
 'Major Distribution',
 'Spin Bout U',
 'The Kind Of Love We Make',
 'Sunroof',
 'The Christmas Song (Merry Christmas To You)',
 'Golden Hour',
 'Jimmy Cooks',
 'Circo Loco',
 'She Had Me At Heads Carolina',
 'On BS',
 'Sleigh Ride',
 'Let It Snow, Let It Snow, Let It Snow',
 'Feliz Navidad',
 "It's Beginning To Look A Lot Like Christmas",
 'About Damn Time',
 'Until I Found You',
 'Thank God',
 'Pussy & Millions',
 'Underneath The Tree',
 'Fall In Love',
 'Bejeweled',
 'Hold Me Closer',
 'Midnight Rain',
 'Wait In The Truck',
 'Rock And A Hard Place',
 'What My World Spins Around',
 'Half Of Me',
 'Hotel Lobby (Unc And Phew)',
 'Maroon',
 'Victoria’s Secret',
 "Don't Come Lookin'",
 'Son Of A Sinner',
 'Privileged Rappers',
 'Shirt',
 "Star Walkin' (League Of Legends Worlds Anthem)",
 'Karma',
 'BackOutsideBoyz',
 "You're On Your Own, Kid",
 'Broke Boys',
 'Snow On The Beach',
 'Hours In Silence',
 'Whiskey On You',
 'Romantic Homicide',
 'Vigilante Shit',
 'Free Mind',
 'Billie Eilish.',
 'Break My Heart',
 'Jumbotron Shit Poppin',
 'Question...?',
 'No Se Va',
 'Heyy',
 'California Breeze',
 'Calm Down',
 'Country On',
 'Mastermind',
 'Treacherous Twins',
 'Heart Like A Truck',
 'Pick Me Up',
 'Down In Atlanta',
 'Labyrinth',
 'Freestyle',
 'Miss You',
 'Sweet Nothing',
 'All Mine',
 'La Bachata',
 'Got It Right',
 'Die For You',
 'Down Home',
 'Going, Going, Gone',
 'Middle Of The Ocean',
 'More M’s']

In [125]:
artist=[]
for i in url:
    driver.get(i)
    time.sleep(5)
    try:
        artists=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[1]/span')
        for u in artists:
            artist.append(u.text)
    except NoSuchElementException:
        artist.append('-')

In [126]:
artist

['Taylor Swift',
 'Drake & 21 Savage',
 'Sam Smith & Kim Petras',
 'Steve Lacy',
 'Mariah Carey',
 'Brenda Lee',
 'David Guetta & Bebe Rexha',
 'Harry Styles',
 'Bobby Helms',
 'Burl Ives',
 'Rihanna',
 'The Weeknd',
 'Morgan Wallen',
 'Chris Brown',
 'Nicki Minaj',
 'Beyonce',
 'Zach Bryan',
 'Post Malone Featuring Doja Cat',
 'Andy Williams',
 'Morgan Wallen',
 'Lil Uzi Vert',
 'GloRilla & Cardi B',
 'Wham!',
 'Meghan Trainor',
 'Doja Cat',
 'Taylor Swift',
 'OneRepublic',
 'Bad Bunny',
 'Future Featuring Drake & Tems',
 'Drake & 21 Savage',
 'Drake & 21 Savage',
 'Luke Combs',
 'Nicky Youre & dazy',
 'Nat King Cole',
 'JVKE',
 'Drake Featuring 21 Savage',
 'Drake & 21 Savage',
 'Cole Swindell',
 'Drake & 21 Savage',
 'The Ronettes',
 'Dean Martin',
 'Jose Feliciano',
 'Perry Como And The Fontane Sisters With Mitchell Ayres And His Orchestra',
 'Lizzo',
 'Stephen Sanchez',
 'Kane Brown With Katelyn Brown',
 'Drake & 21 Savage Featuring Travis Scott',
 'Kelly Clarkson',
 'Bailey Zimmerman',
 'Taylor Swift',
 'Elton John & Britney Spears',
 'Taylor Swift',
 'HARDY Featuring Lainey Wilson',
 'Bailey Zimmerman',
 'Jordan Davis',
 'Thomas Rhett Featuring Riley Green',
 'Quavo & Takeoff',
 'Taylor Swift',
 'Jax',
 'Jackson Dean',
 'Jelly Roll',
 'Drake & 21 Savage',
 'SZA',
 'Lil Nas X',
 'Taylor Swift',
 'Drake',
 'Taylor Swift',
 'Drake & 21 Savage',
 'Taylor Swift Featuring Lana Del Rey',
 'Drake & 21 Savage',
 'Nate Smith',
 'd4vd',
 'Taylor Swift',
 'Tems',
 'Armani White',
 'Rod Wave',
 'Drake',
 'Taylor Swift',
 'Grupo Frontera',
 'Lil Baby',
 'Lil Baby',
 'Rema & Selena Gomez',
 'Luke Bryan',
 'Taylor Swift',
 'Drake & 21 Savage',
 'Lainey Wilson',
 'Gabby Barrett',
 'Pharrell Williams & Travis Scott',
 'Taylor Swift',
 'Lil Baby',
 'Oliver Tree & Robin Schulz',
 'Taylor Swift',
 'Brent Faiyaz',
 'Manuel Turizo',
 'Rod Wave',
 'Joji',
 'Jimmie Allen',
 'Luke Combs',
 'Drake',
 'Drake & 21 Savage']

In [129]:
lwr=[]
for i in url:
    driver.get(i)
    time.sleep(5)
    try:
        lwrs=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[4]/span')
        for u in lwrs:
            lwr.append(u.text)
    except NoSuchElementException:
        lwr.append('-')

In [130]:
lwr

['1',
 '2',
 '3',
 '4',
 '25',
 '41',
 '7',
 '5',
 '50',
 '-',
 '8',
 '12',
 '13',
 '17',
 '11',
 '20',
 '19',
 '16',
 '-',
 '23',
 '47',
 '29',
 '-',
 '40',
 '18',
 '21',
 '24',
 '32',
 '30',
 '6',
 '9',
 '36',
 '28',
 '-',
 '42',
 '27',
 '14',
 '31',
 '10',
 '-',
 '-',
 '-',
 '-',
 '38',
 '56',
 '43',
 '15',
 '-',
 '54',
 '35',
 '46',
 '33',
 '51',
 '57',
 '60',
 '53',
 '59',
 '39',
 '61',
 '66',
 '63',
 '22',
 '55',
 '64',
 '45',
 '26',
 '48',
 '34',
 '49',
 '37',
 '74',
 '68',
 '62',
 '75',
 '71',
 '91',
 '52',
 '65',
 '79',
 '78',
 '76',
 '82',
 '85',
 '70',
 '58',
 '86',
 '90',
 '-',
 '73',
 '84',
 '87',
 '77',
 '83',
 '92',
 '-',
 '72',
 '-',
 '99',
 '67',
 '69']

In [131]:
peak_pos=[]
for i in url:
    driver.get(i)
    time.sleep(5)
    try:
        peak_poss=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[5]/span')
        for u in peak_poss:
            peak_pos.append(u.text)
    except NoSuchElementException:
        peak_pos.append('-')

In [132]:
peak_pos

['1',
 '2',
 '1',
 '1',
 '1',
 '2',
 '7',
 '1',
 '3',
 '4',
 '2',
 '12',
 '5',
 '14',
 '1',
 '13',
 '12',
 '3',
 '5',
 '9',
 '21',
 '9',
 '7',
 '24',
 '10',
 '2',
 '6',
 '5',
 '1',
 '3',
 '5',
 '8',
 '4',
 '11',
 '35',
 '1',
 '8',
 '16',
 '4',
 '10',
 '8',
 '6',
 '12',
 '1',
 '38',
 '22',
 '6',
 '12',
 '29',
 '6',
 '6',
 '5',
 '51',
 '24',
 '41',
 '52',
 '57',
 '3',
 '35',
 '50',
 '31',
 '7',
 '11',
 '32',
 '9',
 '9',
 '8',
 '12',
 '4',
 '11',
 '44',
 '33',
 '10',
 '46',
 '58',
 '76',
 '16',
 '7',
 '57',
 '21',
 '4',
 '74',
 '72',
 '13',
 '14',
 '86',
 '69',
 '88',
 '14',
 '63',
 '84',
 '15',
 '42',
 '67',
 '95',
 '53',
 '88',
 '98',
 '15',
 '18']

In [133]:
woc=[]
for i in url:
    driver.get(i)
    time.sleep(5)
    try:
        wocs=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[6]/span')
        for u in wocs:
            woc.append(u.text)
    except NoSuchElementException:
        woc.append('-')

In [134]:
woc

['5',
 '3',
 '9',
 '21',
 '53',
 '47',
 '13',
 '34',
 '44',
 '27',
 '4',
 '17',
 '28',
 '11',
 '15',
 '15',
 '31',
 '25',
 '28',
 '54',
 '6',
 '9',
 '26',
 '5',
 '25',
 '5',
 '24',
 '29',
 '30',
 '3',
 '3',
 '23',
 '26',
 '33',
 '13',
 '23',
 '3',
 '26',
 '3',
 '17',
 '20',
 '21',
 '13',
 '32',
 '21',
 '11',
 '3',
 '16',
 '30',
 '5',
 '13',
 '5',
 '12',
 '24',
 '15',
 '14',
 '20',
 '5',
 '17',
 '13',
 '21',
 '3',
 '4',
 '9',
 '5',
 '3',
 '5',
 '3',
 '5',
 '3',
 '23',
 '12',
 '5',
 '19',
 '11',
 '2',
 '3',
 '5',
 '9',
 '7',
 '6',
 '12',
 '14',
 '5',
 '3',
 '2',
 '17',
 '1',
 '5',
 '11',
 '5',
 '5',
 '16',
 '14',
 '1',
 '3',
 '4',
 '2',
 '3',
 '3']

In [135]:
billboard_100=pd.DataFrame({'Song Name':name,'Artist':artist,'Last week rank':lwr,
                           'Peak postion':peak_pos,'Weeks on chart':woc})
billboard_100

,Song Name,Artist,Last week rank,Peak postion,Weeks on chart
0,Anti-Hero,Taylor Swift,1,1,5
1,Rich Flex,Drake & 21 Savage,2,2,3
2,Unholy,Sam Smith & Kim Petras,3,1,9
3,Bad Habit,Steve Lacy,4,1,21
4,All I Want For Christmas Is You,Mariah Carey,25,1,53
...,...,...,...,...,...
95,Die For You,Joji,72,53,3
96,Down Home,Jimmie Allen,-,88,4
97,"Going, Going, Gone",Luke Combs,99,98,2
98,Middle Of The Ocean,Drake,67,15,3
99,More M’s,Drake & 21 Savage,69,18,3

In [136]:
driver.close()

# 7. Scrape the details of Data science recruiters from naukri.com.
- Url = https://www.naukri.com/
- You have to find the following details:
- A) Name
- B) Designation
- C) Company
- D) Skills they hire for
- E) Location
- Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
- click on search. All this should be done through code

In [25]:
#connecting to driver
driver=webdriver.Chrome(r"D:\softwares\chromedriver_win32\chromedriver.exe")

#maximizing browser window
driver.maximize_window()

In [26]:
#opening naukri.com website
url='  https://www.naukri.com/hr-recruiters-consultants'
driver.get(url)
time.sleep(5)

In [27]:
search_option=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
search_option.send_keys('Data Science')

In [28]:
search_button= driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button')
search_button.click()

In [9]:
url=[]
link=driver.find_elements(By.XPATH,'/html/body/div[2]/div[2]/div[1]/div[2]/div/div/div/ul/li[1]/a')
for i  in link:
    url.append(i.get_attribute('href'))

In [10]:
url

['https://www.naukri.com/recruiters/browse-all-recruiters']

In [29]:
name=[]
time.sleep(5)
try:
    names=driver.find_elements(By.XPATH,'//span[@class="fl ellipsis"]')
    for u in names:
        name.append(u.text)
except NoSuchElementException:
    name.append('-')

In [30]:
name

['Aakash Harit',
 'shravan Kumar Gaddam',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'subhas patel',
 'Abhishek - Only Analytics Hiring - India and',
 'Institute for Financial Management and Resear',
 'Balu Ramesh',
 'Asif Lucknowi',
 'InstaFinancials',
 'Kalpana Dumpala',
 'Mubarak',
 'Kushal Rastogi',
 'Mahesh Babu Channa',
 'Vaishnavi Kudalkar',
 'Priyanka Akiri',
 'Kapil Devang',
 'Sakshi Chhikara',
 'Ruchi Dhote',
 'Manisha Yadav',
 'Riya Rajesh',
 'Rashmi Bhattacharjee',
 'Faizan Kareem',
 'Rithika dadwal',
 'Sandhya Khandagale',
 'Shaun Rao',
 'Azahar Shaikh',
 'Manas',
 'kumar',
 'Sunil Vedula',
 'Rajat Kumar',
 'Dhruv Dev Dubey',
 'Jayanth N',
 'Daniel Vaz',
 'Avodha',
 'Priya Khare',
 'Amit Sharma',
 'Kanan',
 'Shashikant Chaudhary',
 'Brad',
 'Rutuja Pawar',
 'Madhusudhan Sridhar',
 'Ankit Sinha',
 'Gaurav Chouhan',
 'Rashi Kacker',
 'Ashwini',
 'Balaji Kolli',
 'Rajani Nagaraj',
 'ROHIT Kumar',
 'Amir Chowdhury']

In [32]:
designation=[]
time.sleep(5)
try:
    designations=driver.find_elements(By.XPATH,'//span[@class="ellipsis clr"]')
    for u in designations:
        designation.append(u.text)
except NoSuchElementException:
    designation.append('-')

In [33]:
designation

['HR Manager',
 'Company Recruiter',
 'Company HR',
 'Company Recruiter',
 'Founder CEO',
 'Recruitment Lead Consultant',
 'Programme Manager',
 'HR Administrator',
 'Director',
 'Human Resource',
 'Executive Hiring',
 'Company HR',
 'Company HR',
 'HR Team Lead',
 'HR Executive',
 'HR Manager',
 'HR Manager',
 'Assistant Manager HR',
 'Senior Executive Talent Acquisition',
 'HR Executive',
 'Manager Talent Acquisition',
 'HR Head',
 'HR MANAGER',
 'HR Recruiter',
 'HR Recruiter',
 'Manager Human Resources',
 'Company Recruiter',
 'Lead Talent acquisition',
 'Proprietor',
 'CEO',
 'Founder CEO',
 'Company Recruitment Head',
 'Project Manager',
 'Partner',
 'Business Development Associate',
 'Senior Manager',
 'Consultant',
 'senior technology instructor',
 'HR Recruiter/HR Excutive',
 'Manager, Technical Recruiting',
 'Technical Recruiter',
 'Erp Implementer',
 'Head Analytics',
 'Chief Technical Officer',
 'Sr Product Manager',
 'Director Global Delivery',
 'Co Founder',
 'HR Manager',
 'Architect',
 'Managing Partner']

In [40]:
company=[]
time.sleep(5)
try:
    companys=driver.find_elements(By.XPATH,'//p[@class="highlightable"]/a[2]')
    for u in companys:
        company.append(u.text)
except NoSuchElementException:
    company.append('-')

In [45]:
len(company)

50

In [46]:
location=[]
time.sleep(5)
try:
    locations=driver.find_elements(By.XPATH,'//p[@class="highlightable"]/span/small')
    for u in locations:
        location.append(u.text)
except NoSuchElementException:
    location.append('-')

In [48]:
len(location)

48

In [49]:
skill=[]
time.sleep(5)
try:
    skills=driver.find_elements(By.XPATH,'//div[@class="hireSec highlightable"]')
    for u in skills:
        skill.append(u.text)
except NoSuchElementException:
    skill.append('-')

In [51]:
len(skill)

50

In [52]:
naukri_data=pd.DataFrame({'Name':name[:48],'Designation':designation[:48],'Company':company[:48],'Skills they hire for':skill[:48]
                         ,'Location':location[:48]})
naukri_data

,Name,Designation,Company,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
13,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
14,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",Mumbai
15,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
28,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Delhi
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Mysoru / Mysore
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mumbai
33,Daniel Vaz,Partner,Aquis Search,"c++, Core Java, kdb, high frequency trading, h...",Hyderabad / Secunderabad
34,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Bengaluru / Bangalore
35,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",New Delhi
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Chennai
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Salt Lake City
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Pune
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
42,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Indore
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",MYSORE
45,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Hyderabad / Secunderabad
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Bengaluru / Bangalore
47,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Mumbai

In [53]:
driver.close()

# 8. Scrape the details of Highest selling novels.
- Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
- You have to find the following details:
- A) Book name
- B) Author name
- C) Volumes sold
- D) Publisher
- E) Genre

In [3]:
#connecting to driver
driver=webdriver.Chrome(r"D:\softwares\chromedriver_win32\chromedriver.exe")

#maximizing browser window
driver.maximize_window()

In [4]:
#opening guardian.com website
url=' https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)
time.sleep(5)

In [6]:
url=[]

link=driver.find_elements(By.XPATH,'/html/body/div/div[2]/div[1]/div[2]/div/a[1]')
for i in link:
    url.append(i.get_attribute('href'))

In [7]:
url

['https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare#list']

In [17]:
name=[]
for i in url:
    driver.get(i)
    time.sleep(2)
    try:
        names=driver.find_elements(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[2]')
        for u in names:
            name.append(u.text)
    except NoSuchElementException:
        name.append('-')

In [18]:
name

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [19]:
a_name=[]
for i in url:
    driver.get(i)
    time.sleep(2)
    try:
        a_names=driver.find_elements(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[3]')
        for u in a_names:
            a_name.append(u.text)
    except NoSuchElementException:
        a_name.append('-')

In [20]:
a_name

['Brown, Dan',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'James, E. L.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Brown, Dan',
 'Rowling, J.K.',
 'James, E. L.',
 'Meyer, Stephenie',
 'Larsson, Stieg',
 'James, E. L.',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Sebold, Alice',
 'Haddon, Mark',
 'Brown, Dan',
 'Bryson, Bill',
 'Larsson, Stieg',
 'Meyer, Stephenie',
 'Carle, Eric',
 'Donaldson, Julia',
 'Oliver, Jamie',
 'Hosseini, Khaled',
 'Nicholls, David',
 'Hosseini, Khaled',
 'Larsson, Stieg',
 'Niffenegger, Audrey',
 'McEwan, Ian',
 'Fielding, Helen',
 'Clarkson, Jeremy',
 'Bernieres, Louis de',
 'Kay, Peter',
 'Martel, Yann',
 'Stephenson, Pamela',
 'Pelzer, Dave',
 'Donaldson, Julia',
 'McCourt, Frank',
 'Faulks, Sebastian',
 'Pullman, Philip',
 'Mosse, Kate',
 'Rowling, J.K.',
 'Stockett, Kathryn',
 'Parsons, Tony',
 'Golden, Arthur',
 'McCall Smith, Alexander',
 'Hislop, Victoria',
 'Ahern, Cecelia',
 'McKeith, Gillian',
 'Zafon, Carlos Ruiz',
 'Rowling, J.K.',
 'Grisham, John',
 'Atkins, Robert C.',
 'Pullman, Philip',
 'Truss, Lynne',
 'Smith, Delia',
 'Harris, Joanne',
 'Boyne, John',
 'Picoult, Jodi',
 'Pullman, Philip',
 'Lee, Harper',
 'Gray, John',
 'French, Dawn',
 'Lewycka, Marina',
 'Harris, Thomas',
 'Tolkien, J. R. R.',
 'Moore, Michael',
 'Rubenfeld, Jed',
 'Osbourne, Sharon',
 'Coelho, Paulo',
 "O'Grady, Paul",
 'Bryson, Bill',
 'Oliver, Jamie',
 'Fielding, Helen',
 'Oliver, Jamie',
 'McKenna, Paul',
 'Bryson, Bill',
 'Grisham, John',
 'Levy, Andrea',
 'Lawson, Nigella',
 'Ali, Monica',
 'Edwards, Kim',
 'Donaldson, Julia',
 'Hornby, Nick',
 'Brand, Russell',
 'Dawkins, Richard',
 '0',
 'Smith, Zadie',
 'Morton, Kate',
 'Zusak, Markus',
 'Binchy, Maeve',
 'Harris, Robert',
 'Oliver, Jamie',
 'Collins, Suzanne',
 'Pelzer, Dave',
 'Oliver, Jamie']

In [22]:
volume=[]
for i in url:
    driver.get(i)
    time.sleep(2)
    try:
        volums=driver.find_elements(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[4]')
        for u in volums:
            volume.append(u.text)
    except NoSuchElementException:
        volume.append('-')

In [23]:
volume

['5,094,805',
 '4,475,152',
 '4,200,654',
 '4,179,479',
 '3,758,936',
 '3,583,215',
 '3,484,047',
 '3,377,906',
 '3,193,946',
 '2,950,264',
 '2,479,784',
 '2,315,405',
 '2,233,570',
 '2,193,928',
 '2,183,031',
 '2,152,737',
 '2,062,145',
 '2,052,876',
 '2,005,598',
 '1,979,552',
 '1,928,900',
 '1,852,919',
 '1,814,784',
 '1,787,118',
 '1,783,535',
 '1,781,269',
 '1,743,266',
 '1,629,119',
 '1,616,068',
 '1,583,992',
 '1,555,135',
 '1,546,886',
 '1,539,428',
 '1,508,205',
 '1,489,403',
 '1,352,318',
 '1,310,207',
 '1,310,176',
 '1,231,957',
 '1,217,712',
 '1,208,711',
 '1,204,058',
 '1,184,967',
 '1,181,503',
 '1,181,093',
 '1,153,181',
 '1,132,336',
 '1,130,802',
 '1,126,337',
 '1,115,549',
 '1,108,328',
 '1,107,379',
 '1,104,403',
 '1,092,349',
 '1,090,847',
 '1,087,262',
 '1,054,196',
 '1,037,160',
 '1,023,688',
 '1,015,956',
 '1,009,873',
 '1,004,414',
 '1,003,780',
 '1,002,314',
 '998,213',
 '992,846',
 '986,753',
 '986,115',
 '970,509',
 '967,466',
 '963,353',
 '962,515',
 '959,496',
 '956,114',
 '945,640',
 '931,312',
 '925,425',
 '924,695',
 '906,968',
 '905,086',
 '890,847',
 '869,671',
 '869,659',
 '862,602',
 '856,540',
 '845,858',
 '842,535',
 '828,215',
 '820,563',
 '816,907',
 '816,585',
 '815,586',
 '814,370',
 '809,641',
 '808,900',
 '807,311',
 '794,201',
 '792,187',
 '791,507',
 '791,095']

In [24]:
publisher=[]
for i in url:
    driver.get(i)
    time.sleep(2)
    try:
        publishers=driver.find_elements(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[5]')
        for u in publishers:
            publisher.append(u.text)
    except NoSuchElementException:
        publisher.append('-')

In [25]:
publisher

['Transworld',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Random House',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Transworld',
 'Bloomsbury',
 'Random House',
 'Little, Brown Book',
 'Quercus',
 'Random House',
 'Transworld',
 'Little, Brown Book',
 'Transworld',
 'Little, Brown Book',
 'Pan Macmillan',
 'Random House',
 'Transworld',
 'Transworld',
 'Quercus',
 'Little, Brown Book',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Bloomsbury',
 'Hodder & Stoughton',
 'Bloomsbury',
 'Quercus',
 'Random House',
 'Random House',
 'Pan Macmillan',
 'Penguin',
 'Random House',
 'Random House',
 'Canongate',
 'HarperCollins',
 'Orion',
 'Pan Macmillan',
 'HarperCollins',
 'Random House',
 'Scholastic Ltd.',
 'Orion',
 'Bloomsbury',
 'Penguin',
 'HarperCollins',
 'Random House',
 'Little, Brown Book',
 'Headline',
 'HarperCollins',
 'Penguin',
 'Orion',
 'Bloomsbury',
 'Random House',
 'Random House',
 'Scholastic Ltd.',
 'Profile Books Group',
 'Random House',
 'Transworld',
 'Random House Childrens Books G',
 'Hodder & Stoughton',
 'Scholastic Ltd.',
 'Random House',
 'HarperCollins',
 'Random House',
 'Penguin',
 'Random House',
 'HarperCollins',
 'Penguin',
 'Headline',
 'Little, Brown Book',
 'HarperCollins',
 'Transworld',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Transworld',
 'Transworld',
 'Random House',
 'Headline',
 'Random House',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Hodder & Stoughton',
 'Transworld',
 'D.C. Thomson',
 'Penguin',
 'Pan Macmillan',
 'Transworld',
 'Orion',
 'Random House',
 'Penguin',
 'Scholastic Ltd.',
 'Orion',
 'Penguin']

In [26]:
genre=[]
for i in url:
    driver.get(i)
    time.sleep(2)
    try:
        genres=driver.find_elements(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[6]')
        for u in genres:
            genre.append(u.text)
    except NoSuchElementException:
        genre.append('-')

In [27]:
genre

['Crime, Thriller & Adventure',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Romance & Sagas',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 "Children's Fiction",
 'Romance & Sagas',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Romance & Sagas',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Popular Science',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Picture Books',
 'Picture Books',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Humour: Collections & General',
 'General & Literary Fiction',
 'Autobiography: General',
 'General & Literary Fiction',
 'Biography: The Arts',
 'Autobiography: General',
 'Picture Books',
 'Autobiography: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Science Fiction & Fantasy',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Fitness & Diet',
 'General & Literary Fiction',
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 'Fitness & Diet',
 'Young Adult Fiction',
 'Usage & Writing Guides',
 'Food & Drink: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Popular Culture & Media: General Interest',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Science Fiction & Fantasy',
 'Current Affairs & Issues',
 'Crime, Thriller & Adventure',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Travel Writing',
 'Food & Drink: General',
 'General & Literary Fiction',
 'National & Regional Cuisine',
 'Fitness & Diet',
 'Travel Writing',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Picture Books',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Popular Science',
 "Children's Annuals",
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Food & Drink: General',
 'Young Adult Fiction',
 'Biography: General',
 'Food & Drink: General']

In [28]:
books=pd.DataFrame({'Book name':name,'Author name':a_name,'Volume sold':volume,'Publisher':publisher,'Genre':genre})
books

,Book name,Author name,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [29]:
driver.close()

# 9. Scrape the details most watched tv series of all time from imdb.com.
- Url = https://www.imdb.com/list/ls095964455/
- You have to find the following details:
- A) Name
- B) Year span
- C) Genre
- D) Run time
- E) Ratings
- F) Votes

In [139]:
#connecting to driver
driver=webdriver.Chrome(r"D:\softwares\chromedriver_win32\chromedriver.exe")

#maximizing browser window
driver.maximize_window()

In [140]:
#opening guardian.com website
url=' https://www.imdb.com/list/ls095964455/'
driver.get(url)
time.sleep(5)

In [158]:
name=[]
names=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')
for i in names:
    name.append(i.text)

In [159]:
name

['Game of Thrones',
 'Stranger Things',
 'The Walking Dead',
 '13 Reasons Why',
 'The 100',
 'Orange Is the New Black',
 'Riverdale',
 "Grey's Anatomy",
 'The Flash',
 'Arrow',
 'Money Heist',
 'The Big Bang Theory',
 'Black Mirror',
 'Sherlock',
 'Vikings',
 'Pretty Little Liars',
 'The Vampire Diaries',
 'American Horror Story',
 'Breaking Bad',
 'Lucifer',
 'Supernatural',
 'Prison Break',
 'How to Get Away with Murder',
 'Teen Wolf',
 'The Simpsons',
 'Once Upon a Time',
 'Narcos',
 'Daredevil',
 'Friends',
 'How I Met Your Mother',
 'Suits',
 'Mr. Robot',
 'The Originals',
 'Supergirl',
 'Gossip Girl',
 'Sense8',
 'Gotham',
 'Westworld',
 'Jessica Jones',
 'Modern Family',
 'Rick and Morty',
 'Shadowhunters',
 'The End of the F***ing World',
 'House of Cards',
 'Dark',
 'Elite',
 'Sex Education',
 'Shameless',
 'New Girl',
 'Agents of S.H.I.E.L.D.',
 'You',
 'Dexter',
 'Fear the Walking Dead',
 'Family Guy',
 'The Blacklist',
 'Lost',
 'Peaky Blinders',
 'House',
 'Quantico',
 'Orphan Black',
 'Homeland',
 'Blindspot',
 "DC's Legends of Tomorrow",
 "The Handmaid's Tale",
 'Chilling Adventures of Sabrina',
 'The Good Doctor',
 'Jane the Virgin',
 'Glee',
 'South Park',
 'Brooklyn Nine-Nine',
 'Under the Dome',
 'The Umbrella Academy',
 'True Detective',
 'The OA',
 'Desperate Housewives',
 'Better Call Saul',
 'Bates Motel',
 'The Punisher',
 'Atypical',
 'Dynasty',
 'This Is Us',
 'The Good Place',
 'Iron Fist',
 'The Rain',
 'Mindhunter',
 'Revenge',
 'Luke Cage',
 'Scandal',
 'The Defenders',
 'Big Little Lies',
 'Insatiable',
 'The Mentalist',
 'The Crown',
 'Chernobyl',
 'iZombie',
 'Reign',
 'A Series of Unfortunate Events',
 'Criminal Minds',
 'Scream: The TV Series',
 'The Haunting of Hill House']

In [161]:
year=[]
years=driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')
for i in years:
    year.append(i.text)

In [162]:
year

['(2011–2019)',
 '(2016– )',
 '(2010–2022)',
 '(2017–2020)',
 '(2014–2020)',
 '(2013–2019)',
 '(2017– )',
 '(2005– )',
 '(2014–2023)',
 '(2012–2020)',
 '(2017–2021)',
 '(2007–2019)',
 '(2011–2019)',
 '(2010–2017)',
 '(2013–2020)',
 '(2010–2017)',
 '(2009–2017)',
 '(2011– )',
 '(2008–2013)',
 '(2016–2021)',
 '(2005–2020)',
 '(2005–2017)',
 '(2014–2020)',
 '(2011–2017)',
 '(1989– )',
 '(2011–2018)',
 '(2015–2017)',
 '(2015–2018)',
 '(1994–2004)',
 '(2005–2014)',
 '(2011–2019)',
 '(2015–2019)',
 '(2013–2018)',
 '(2015–2021)',
 '(2007–2012)',
 '(2015–2018)',
 '(2014–2019)',
 '(2016–2022)',
 '(2015–2019)',
 '(2009–2020)',
 '(2013– )',
 '(2016–2019)',
 '(2017–2019)',
 '(2013–2018)',
 '(2017–2020)',
 '(2018– )',
 '(2019– )',
 '(2011–2021)',
 '(2011–2018)',
 '(2013–2020)',
 '(2018– )',
 '(2006–2013)',
 '(2015– )',
 '(1999– )',
 '(2013– )',
 '(2004–2010)',
 '(2013–2022)',
 '(2004–2012)',
 '(2015–2018)',
 '(2013–2017)',
 '(2011–2020)',
 '(2015–2020)',
 '(2016–2022)',
 '(2017– )',
 '(2018–2020)',
 '(2017– )',
 '(2014–2019)',
 '(2009–2015)',
 '(1997– )',
 '(2013–2021)',
 '(2013–2015)',
 '(2019–2023)',
 '(2014–2019)',
 '(2016–2019)',
 '(2004–2012)',
 '(2015–2022)',
 '(2013–2017)',
 '(2017–2019)',
 '(2017–2021)',
 '(2017–2022)',
 '(2016–2022)',
 '(2016–2020)',
 '(2017–2018)',
 '(2018–2020)',
 '(2017–2019)',
 '(2011–2015)',
 '(2016–2018)',
 '(2012–2018)',
 '(2017)',
 '(2017–2019)',
 '(2018–2019)',
 '(2008–2015)',
 '(2016– )',
 '(2019)',
 '(2015–2019)',
 '(2013–2017)',
 '(2017–2019)',
 '(2005– )',
 '(2015–2019)',
 '(2018)']

In [163]:
genre=[]
genres=driver.find_elements(By.XPATH,'//span[@class="genre"]')
for i in genres:
    genre.append(i.text)

In [164]:
genre

['Action, Adventure, Drama',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Drama, Mystery, Thriller',
 'Drama, Mystery, Sci-Fi',
 'Comedy, Crime, Drama',
 'Crime, Drama, Mystery',
 'Drama, Romance',
 'Action, Adventure, Drama',
 'Action, Adventure, Crime',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Drama, Mystery, Sci-Fi',
 'Crime, Drama, Mystery',
 'Action, Adventure, Drama',
 'Drama, Mystery, Romance',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Sci-Fi',
 'Crime, Drama, Thriller',
 'Crime, Drama, Fantasy',
 'Drama, Fantasy, Horror',
 'Action, Crime, Drama',
 'Crime, Drama, Mystery',
 'Action, Drama, Fantasy',
 'Animation, Comedy',
 'Adventure, Fantasy, Romance',
 'Biography, Crime, Drama',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Comedy, Romance',
 'Comedy, Drama',
 'Crime, Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Action, Adventure, Drama',
 'Drama, Romance',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Action, Drama, Fantasy',
 'Adventure, Comedy, Crime',
 'Drama',
 'Crime, Drama, Mystery',
 'Crime, Drama, Thriller',
 'Comedy, Drama',
 'Comedy, Drama',
 'Comedy, Romance',
 'Action, Adventure, Drama',
 'Crime, Drama, Romance',
 'Crime, Drama, Mystery',
 'Drama, Horror, Sci-Fi',
 'Animation, Comedy',
 'Crime, Drama, Mystery',
 'Adventure, Drama, Fantasy',
 'Crime, Drama',
 'Drama, Mystery',
 'Crime, Drama, Mystery',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Action, Crime, Drama',
 'Action, Adventure, Drama',
 'Drama, Sci-Fi, Thriller',
 'Drama, Fantasy, Horror',
 'Drama',
 'Comedy',
 'Comedy, Drama, Music',
 'Animation, Comedy',
 'Comedy, Crime',
 'Drama, Mystery, Sci-Fi',
 'Action, Adventure, Comedy',
 'Crime, Drama, Mystery',
 'Drama, Fantasy, Mystery',
 'Comedy, Drama, Mystery',
 'Crime, Drama',
 'Drama, Horror, Mystery',
 'Action, Crime, Drama',
 'Comedy, Drama',
 'Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Fantasy',
 'Action, Adventure, Crime',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Drama, Mystery, Thriller',
 'Action, Crime, Drama',
 'Drama, Thriller',
 'Action, Adventure, Crime',
 'Crime, Drama, Mystery',
 'Comedy, Drama, Thriller',
 'Crime, Drama, Mystery',
 'Biography, Drama, History',
 'Drama, History, Thriller',
 'Comedy, Crime, Drama',
 'Drama',
 'Adventure, Comedy, Drama',
 'Crime, Drama, Mystery',
 'Comedy, Crime, Drama',
 'Drama, Horror, Mystery']

In [165]:
time=[]
times=driver.find_elements(By.XPATH,'//span[@class="runtime"]')
for i in times:
    time.append(i.text)

In [166]:
time

['57 min',
 '51 min',
 '44 min',
 '60 min',
 '43 min',
 '59 min',
 '45 min',
 '41 min',
 '43 min',
 '42 min',
 '70 min',
 '22 min',
 '60 min',
 '88 min',
 '44 min',
 '44 min',
 '43 min',
 '60 min',
 '49 min',
 '42 min',
 '44 min',
 '44 min',
 '43 min',
 '41 min',
 '22 min',
 '60 min',
 '49 min',
 '54 min',
 '22 min',
 '22 min',
 '44 min',
 '49 min',
 '45 min',
 '43 min',
 '42 min',
 '60 min',
 '42 min',
 '62 min',
 '56 min',
 '22 min',
 '23 min',
 '42 min',
 '25 min',
 '51 min',
 '60 min',
 '60 min',
 '45 min',
 '46 min',
 '22 min',
 '45 min',
 '45 min',
 '53 min',
 '44 min',
 '22 min',
 '43 min',
 '44 min',
 '60 min',
 '44 min',
 '42 min',
 '44 min',
 '55 min',
 '42 min',
 '42 min',
 '60 min',
 '60 min',
 '41 min',
 '60 min',
 '44 min',
 '22 min',
 '22 min',
 '43 min',
 '60 min',
 '55 min',
 '60 min',
 '45 min',
 '46 min',
 '45 min',
 '53 min',
 '30 min',
 '42 min',
 '45 min',
 '22 min',
 '55 min',
 '45 min',
 '60 min',
 '44 min',
 '55 min',
 '43 min',
 '50 min',
 '60 min',
 '45 min',
 '43 min',
 '58 min',
 '330 min',
 '42 min',
 '42 min',
 '50 min',
 '42 min',
 '45 min',
 '572 min']

In [174]:
ratings=[]
ratingss=driver.find_elements(By.XPATH,'//div[@class="ipl-rating-star small"]')
for i in ratingss:
    ratings.append(i.text)

In [175]:
ratings

['9.2',
 '8.7',
 '8.1',
 '7.5',
 '7.6',
 '8.1',
 '6.6',
 '7.6',
 '7.6',
 '7.5',
 '8.2',
 '8.2',
 '8.8',
 '9.1',
 '8.5',
 '7.4',
 '7.7',
 '8',
 '9.5',
 '8.1',
 '8.4',
 '8.3',
 '8.1',
 '7.7',
 '8.7',
 '7.7',
 '8.8',
 '8.6',
 '8.9',
 '8.3',
 '8.5',
 '8.6',
 '8.3',
 '6.2',
 '7.5',
 '8.2',
 '7.8',
 '8.5',
 '7.9',
 '8.5',
 '9.1',
 '6.5',
 '8.1',
 '8.7',
 '8.7',
 '7.3',
 '8.4',
 '8.6',
 '7.8',
 '7.5',
 '7.7',
 '8.7',
 '6.8',
 '8.2',
 '8',
 '8.3',
 '8.8',
 '8.7',
 '6.7',
 '8.3',
 '8.3',
 '7.3',
 '6.8',
 '8.4',
 '7.4',
 '8.1',
 '7.9',
 '6.8',
 '8.7',
 '8.4',
 '6.5',
 '7.9',
 '8.9',
 '7.8',
 '7.6',
 '8.9',
 '8.1',
 '8.5',
 '8.3',
 '7.2',
 '8.7',
 '8.2',
 '6.4',
 '6.3',
 '8.6',
 '7.8',
 '7.3',
 '7.7',
 '7.2',
 '8.5',
 '6.5',
 '8.1',
 '8.7',
 '9.4',
 '7.8',
 '7.4',
 '7.8',
 '8.1',
 '7.1',
 '8.6']

In [180]:
votes=[]
votess=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[4]/span[2]')
for i in votess:
    votes.append(i.text)

In [181]:
votes

['2,089,164',
 '1,178,793',
 '988,385',
 '292,758',
 '251,904',
 '302,839',
 '145,470',
 '308,729',
 '346,268',
 '431,916',
 '475,846',
 '806,877',
 '545,352',
 '923,973',
 '531,485',
 '167,995',
 '322,171',
 '319,509',
 '1,871,491',
 '324,250',
 '445,466',
 '535,139',
 '152,219',
 '148,872',
 '407,381',
 '225,384',
 '421,795',
 '440,719',
 '992,313',
 '682,920',
 '410,712',
 '387,570',
 '136,549',
 '124,405',
 '175,397',
 '154,967',
 '230,904',
 '504,823',
 '215,150',
 '430,438',
 '519,025',
 '64,082',
 '190,714',
 '504,535',
 '384,420',
 '79,516',
 '280,308',
 '243,297',
 '224,978',
 '217,635',
 '240,066',
 '725,275',
 '130,366',
 '339,759',
 '249,645',
 '553,318',
 '545,901',
 '464,718',
 '61,270',
 '111,531',
 '341,956',
 '74,395',
 '105,226',
 '236,800',
 '95,696',
 '95,434',
 '51,110',
 '148,964',
 '369,498',
 '315,944',
 '107,024',
 '248,150',
 '570,134',
 '105,400',
 '129,592',
 '524,704',
 '108,700',
 '236,436',
 '89,389',
 '22,863',
 '144,342',
 '160,559',
 '131,692',
 '37,578',
 '288,542',
 '120,465',
 '131,797',
 '74,307',
 '108,463',
 '199,473',
 '29,099',
 '185,672',
 '216,238',
 '748,143',
 '68,661',
 '50,165',
 '61,423',
 '198,193',
 '41,568',
 '245,104']

In [182]:
imdb_tv=pd.DataFrame({'Name':name,'Year span':year,'Genre':genre,'Run time':time,'Ratings':ratings,'Votes':votes})
imdb_tv

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,089,164"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,178,793"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"988,385"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"292,758"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"251,904"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"50,165"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"61,423"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"198,193"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"41,568"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"245,104"

In [184]:
driver.close()

# 10. Details of Datasets from UCI machine learning repositories.
- Url = https://archive.ics.uci.edu/
- You have to find the following details:
- A) Dataset name
- B) Data type
- C) Task
- D) Attribute type
- E) No of instances
- F) No of attribute
- G) Year
- Note: - from the home page you have to go to the ShowAllDataset page through code.

In [185]:
#connecting to driver
driver=webdriver.Chrome(r"D:\softwares\chromedriver_win32\chromedriver.exe")

#maximizing browser window
driver.maximize_window()

In [188]:
#opening wikipedia.com website
url=' https://archive.ics.uci.edu/'
driver.get(url)
time.sleep(5)

In [190]:
view_tab=driver.find_element(By.XPATH,'//span[@class="whitetext"]/a/font/b')
view_tab.click()

In [203]:
url=[]
link=driver.find_elements(By.XPATH,'/html/body/table[1]/tbody/tr/td[2]/span[2]/a')
for i in link:
    url.append(i.get_attribute('href'))

In [204]:
url

['https://archive.ics.uci.edu/ml/datasets.php']

In [205]:
name=[] 
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        names=driver.find_elements(By.XPATH,'//p[@class="normal"]/b/a')
        for i in names:
            name.append(i.text)
    except NoSuchElementException:
        name.append('-')

In [207]:
name[:10]

['Abalone',
 'Adult',
 'Annealing',
 'Anonymous Microsoft Web Data',
 'Arrhythmia',
 'Artificial Characters',
 'Audiology (Original)',
 'Audiology (Standardized)',
 'Auto MPG',
 'Automobile']

In [210]:
dtype=[] 
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        dtypes=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]/p')
        for i in dtypes:
            dtype.append(i.text)
    except NoSuchElementException:
        dtype.append('-')

In [213]:
dtype[1:11]

['Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ']

In [214]:
task=[] 
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        tasks=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]/p')
        for i in tasks:
            task.append(i.text)
    except NoSuchElementException:
        task.append('-')

In [217]:
task[1:11]

['Classification ',
 'Classification ',
 'Classification ',
 'Recommender-Systems ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ']

In [218]:
att_type=[] 
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        att_types=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]/p')
        for i in att_types:
            att_type.append(i.text)
    except NoSuchElementException:
        att_type.append('-')

In [219]:
att_type[1:11]

['Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical, Integer, Real ']

In [220]:
instances=[] 
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        instancess=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]/p')
        for i in instancess:
            instances.append(i.text)
    except NoSuchElementException:
        instances.append('-')

In [221]:
instances[1:11]

['4177 ',
 '48842 ',
 '798 ',
 '37711 ',
 '452 ',
 '6000 ',
 '226 ',
 '226 ',
 '398 ',
 '205 ']

In [223]:
attribute=[] 
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        attributes=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]/p')
        for i in attributes:
            attribute.append(i.text)
    except NoSuchElementException:
        attribute.append('-')

In [224]:
attribute[1:11]

['8 ', '14 ', '38 ', '294 ', '279 ', '7 ', ' ', '69 ', '8 ', '26 ']

In [225]:
year=[] 
for i in url:
    driver.get(i)
    time.sleep(4)
    try:
        years=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]/p')
        for i in years:
            year.append(i.text)
    except NoSuchElementException:
        year.append('-')

In [226]:
year[1:11]

['1995 ',
 '1996 ',
 ' ',
 '1998 ',
 '1998 ',
 '1992 ',
 '1987 ',
 '1992 ',
 '1993 ',
 '1987 ']

In [227]:
ML_dataset=pd.DataFrame({'Dataset Name':name[:10],'Data type':dtype[1:11],'Task':task[1:11],'Atttribute type':attribute[1:11],
                        'No. of instances':instances[1:11],'No of attribute':attribute[1:11],'Year':year[1:11]})
ML_dataset

,Dataset Name,Data type,Task,Atttribute type,No. of instances,No of attribute,Year
0,Abalone,Multivariate,Classification,8,4177,8,1995
1,Adult,Multivariate,Classification,14,48842,14,1996
2,Annealing,Multivariate,Classification,38,798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,294,37711,294,1998
4,Arrhythmia,Multivariate,Classification,279,452,279,1998
5,Artificial Characters,Multivariate,Classification,7,6000,7,1992
6,Audiology (Original),Multivariate,Classification,,226,,1987
7,Audiology (Standardized),Multivariate,Classification,69,226,69,1992
8,Auto MPG,Multivariate,Regression,8,398,8,1993
9,Automobile,Multivariate,Regression,26,205,26,1987

In [228]:
driver.close()